using Microsoft.AspNet.Identity.Owin;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using WebApplication1;

namespace InternshipSite.Forms
{
    public partial class Listings : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {
            if(IsAdmin())
            {
                btnAddPosting.Visible = true;
                dtlPosting.AutoGenerateDeleteButton = true;
            }
            else
            {
                dtlPosting.AutoGenerateDeleteButton = false;
            }
        }

        protected void grdListings_PreRender(object sender, EventArgs e)
        {
            grdListings.HeaderRow.TableSection = TableRowSection.TableHeader;
        }

        protected bool IsAdmin()
        {
            return User.IsInRole("admin");
        }

        protected void dtlPosting_ItemDeleted(object sender, DetailsViewDeletedEventArgs e)
        {
            grdListings.DataBind();
        }
    }
}